<Query Kind="Statements" />

// 由 Generator.linq 从 06_RequiredMapping_OneSideStrict.linq 生成，请勿手改；Mapper 有改动后重新运行 Generator.linq。

// ---- BothMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class BothMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto ToDto(global::Car car)
    {
        var target = new global::CarDto();
        target.Name = car.Name;
        target.NumberOfSeats = car.NumberOfSeats;
        return target;
    }
}

// ---- SourceStrictMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class SourceStrictMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto ToDto(global::Car car)
    {
        var target = new global::CarDto();
        target.Name = car.Name;
        target.NumberOfSeats = car.NumberOfSeats;
        return target;
    }
}

// ---- TargetStrictMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class TargetStrictMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto ToDto(global::Car car)
    {
        var target = new global::CarDto();
        target.Name = car.Name;
        target.NumberOfSeats = car.NumberOfSeats;
        return target;
    }
}

// ---- MethodLevelMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class MethodLevelMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto ToDto(global::Car car)
    {
        var target = new global::CarDto();
        target.Name = car.Name;
        target.NumberOfSeats = car.NumberOfSeats;
        return target;
    }
}
