<Query Kind="Statements" />

// 由 Generator.linq 从 1_GettingStart.linq 生成，请勿手改；Mapper 有改动后重新运行 Generator.linq。

// ---- CarMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class CarMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto CarToCarDto(global::Car car)
    {
        var target = new global::CarDto();
        target.Name = car.Name;
        target.NumberOfSeats = car.NumberOfSeats;
        target.Color = (global::CarColorDto)car.Color;
        if (car.Manufacturer != null)
        {
            target.ManufacturerId = car.Manufacturer.Id;
            target.ManufacturerName = car.Manufacturer.Name;
        }
        target.EngineHorsepower = car.Engine.Horsepower;
        target.Tires = MapToListOfTireDto(car.Tires);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    private global::TireDto MapToTireDto(global::Tire source)
    {
        var target = new global::TireDto();
        target.Description = source.Description;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    private global::System.Collections.Generic.List<global::TireDto> MapToListOfTireDto(global::System.Collections.Generic.IReadOnlyCollection<global::Tire> source)
    {
        var target = new global::System.Collections.Generic.List<global::TireDto>(source.Count);
        foreach (var item in source)
        {
            target.Add(MapToTireDto(item));
        }
        return target;
    }
}
