<Query Kind="Statements" />

// 由 Generator.linq 从 4_Flattening.linq 生成，请勿手改；Mapper 有改动后重新运行 Generator.linq。

// ---- CarMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class CarMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto CarToCarDto(global::Car car)
    {
        var target = new global::CarDto();
        target.Name = car.Name;
        target.NumberOfSeats = car.NumberOfSeats;
        target.Color = (global::CarColorDto)car.Color;
        if (car.Manufacturer != null)
        {
            target.Producer = MapToProducerDto(car.Manufacturer);
            target.ManufacturerId = car.Manufacturer.Id;
            target.ManufacturerName = car.Manufacturer.Name;
        }
        else
        {
            target.Producer = null;
        }
        target.EngineHorsepower = car.Engine.Horsepower;
        target.Tires = MapToListOfTireDto(car.Tires);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarSummaryDto CarToSummary(global::Car car)
    {
        var target = new global::CarSummaryDto();
        target.Name = car.Name;
        if (car.Manufacturer != null)
        {
            target.Brand = car.Manufacturer.Name;
        }
        target.Hp = car.Engine.Horsepower;
        target.Fuel = car.Engine.FuelType;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarEngineInfoDto CarToEngineInfo(global::Car car)
    {
        var target = new global::CarEngineInfoDto();
        target.Name = car.Name;
        target.Horsepower = car.Engine.Horsepower;
        target.FuelType = car.Engine.FuelType;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::Car SummaryToCar(global::CarSummaryDto summary)
    {
        var target = new global::Car();
        target.Name = summary.Name;
        target.Engine.Horsepower = summary.Hp;
        target.Engine.FuelType = summary.Fuel;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    private global::ProducerDto MapToProducerDto(global::Manufacturer source)
    {
        var target = new global::ProducerDto(source.Id, source.Name);
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    private global::TireDto MapToTireDto(global::Tire source)
    {
        var target = new global::TireDto();
        target.Description = source.Description;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    private global::System.Collections.Generic.List<global::TireDto> MapToListOfTireDto(global::System.Collections.Generic.IReadOnlyCollection<global::Tire> source)
    {
        var target = new global::System.Collections.Generic.List<global::TireDto>(source.Count);
        foreach (var item in source)
        {
            target.Add(MapToTireDto(item));
        }
        return target;
    }
}
