<Query Kind="Statements" />

// 由 Generator.linq 从 2_MapProperty_Ignore.linq 生成，请勿手改；Mapper 有改动后重新运行 Generator.linq。

// ---- CarMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class CarMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto CarToCarDto(global::Car car)
    {
        var target = new global::CarDto();
        target.NumberOfSeats = car.NumberOfSeats;
        target.Color = (global::CarColorDto)car.Color;
        return target;
    }
}
