<Query Kind="Statements" />

// 由 Generator.linq 从 3_PropertyName_CaseInsensitive.linq 生成，请勿手改；Mapper 有改动后重新运行 Generator.linq。

// ---- CaseSensitiveMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class CaseSensitiveMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto ToDto(global::Car car)
    {
        var target = new global::CarDto();
        return target;
    }
}

// ---- CaseInsensitiveMapper.g.cs ----
// <auto-generated />
#nullable enable
public partial class CaseInsensitiveMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.3.1.0")]
    public partial global::CarDto ToDto(global::Car car)
    {
        var target = new global::CarDto();
        target.modelName = car.ModelName;
        target.numberOfSeats = car.NumberOfSeats;
        return target;
    }
}
